### ISSUE TITLE
sekaid can't connect to all public peers

### ISSUE THREAD

**Issue by westaking** [KiraCore/sekai#124]
If sekaid is manually installed and configured, **it can't connect to all public peers** from https://testnet-rpc.kira.network/download/peers.txt

build version : branch testnet-3

After installing sentry with kira manager on another server, 
all settings in config.toml of sentry node were set to the same, 
and persistent_peer set  public peers from https://testnet-rpc.kira.network/download/peers.txt.

The seeds in config.toml are set as follows:
```
seeds = "c2090b7e1141349e4fce27d07b8d5ebb741ad32b@3.11.224.235:16656,d91c46d65921a18469ab05b7c33e542f2301a7c0@3.11.224.235:26656,23bd70d90d13416637626632512cc86833fff8fa@3.11.224.235:36656"
```

everything worked fine on testnet-2
but testnet-3 ....

**Comment by asmodat** [comment]
you can try https://testnet-rpc.kira.network/download/snaps.txt

**Comment by westaking** [comment]
The peers of snaps.txt are also not connected.

**Comment by westaking** [comment]
One peer is connected.

Compared to other cosmos chains, sekaid does not seem to be able to connect to peers smoothly.

**Comment by westaking** [comment]
Only one peer was connected for 2-3 days, but now several peers are connected. 
It is a mystery why the connection rate was low in the beginning.

**Comment by westaking** [comment]
I don't know when it was solved, but the connection seems to be smooth.
