### ISSUE TITLE
priv_sentry : configuring  : starting | VALIDATOR NODE IS NOT PRODUCING BLOCKS

### ISSUE THREAD

**Issue by goganaut** [KiraCore/sekai#137]
![Screenshot_20210605_144452](https://user-images.githubusercontent.com/82846245/120881639-e267d300-c615-11eb-972c-8e494388eabe.png)

in sentry/start.txt
```
^[[0m^[[33;1mWARNINIG: Handshake fialure, expected node id to be '' but got 'secret connection failed'^[[0m
^[[0m^[[33;1mWARNINIG: Seed 'dada33b8a7d96d7e07150284a63c2e2e70c56fa4@209.145.60.203:56656' is NOT reachable!^[[0m
^[[0m^[[33;1mWARNINIG: Handshake fialure, expected node id to be '' but got 'secret connection failed'^[[0m
^[[0m^[[33;1mWARNINIG: Seed 'ace77e8963cd60c9a1dcf1a6fef79de802445bca@194.233.67.103:56656' is NOT reachable!^[[0m
^[[0m^[[36;1mINFO: Final Seeds List:^[[0m
^[[0m^[[36;1m^[[0m
^[[0m^[[36;1mINFO: Peers configuration is available, testing...^[[0m
^[[0m^[[36;1mINFO: Adding extra peer 'tcp://bb858b4adfed80ca0413b61ecbfa8203b61a0c50@priv-sentry.local:26656' to new config^[[0m
+ for peer in $(echo $CFG_persistent_peers | sed "s/,/ /g")
++ echo tcp://7d9e4e6582bbe6175bd172457e9ce79cbe4a023c@validator.local:26656
++ sed 's/tcp\?:\/\///'
+ peer=7d9e4e6582bbe6175bd172457e9ce79cbe4a023c@validator.local:26656
```
logs 

[OkaNode_05062021_kira_dump.zip](https://github.com/KiraCore/sekai/files/6602067/OkaNode_05062021_kira_dump.zip)
[OkaNode_05062021_kira_interx.zip](https://github.com/KiraCore/sekai/files/6602068/OkaNode_05062021_kira_interx.zip)
[OkaNode_05062021_kira_kirascan.zip](https://github.com/KiraCore/sekai/files/6602069/OkaNode_05062021_kira_kirascan.zip)
[OkaNode_05062021_kira_kiraup.zip](https://github.com/KiraCore/sekai/files/6602070/OkaNode_05062021_kira_kiraup.zip)
[OkaNode_05062021_kira_priv_sentry.zip](https://github.com/KiraCore/sekai/files/6602071/OkaNode_05062021_kira_priv_sentry.zip)
[OkaNode_05062021_kira_registry.zip](https://github.com/KiraCore/sekai/files/6602072/OkaNode_05062021_kira_registry.zip)
[OkaNode_05062021_kira_sentry.zip](https://github.com/KiraCore/sekai/files/6602073/OkaNode_05062021_kira_sentry.zip)
[OkaNode_05062021_kira_snapshot.zip](https://github.com/KiraCore/sekai/files/6602074/OkaNode_05062021_kira_snapshot.zip)
[OkaNode_05062021_kira_validator.zip](https://github.com/KiraCore/sekai/files/6602075/OkaNode_05062021_kira_validator.zip)

**Comment by asmodat** [comment]
awiat until your node is synced and submit your key to be whitleisted, not an issue as per above evidence
