### ISSUE TITLE
Validators (staking pool) commission rate have no limits. 

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#431]
### Status quo

 #408 sets validators' commission rate as a parameter of their respective staking pool but there is currently no limits on those rate; `SetStakingPool` doesn't operate any checks:
https://github.com/KiraCore/sekai/blob/971cee61bc1d08814458671d22a0d83c0edb3b33/x/multistaking/keeper/pool.go#L54

### Enhancement

- [ ] There should be an upper limit of `0.5`  (50%) and lower limit of `0.01` (1%). 

### Further considerations : network properties

Unlike for fee rewards with the [ValidatorFeeShare](https://github.com/KiraCore/sekai/blob/55d47a7fee8573efa611100b778e7094e41f6e40/x/gov/types/network_properties.go#L111), there is currently no network properties for validator's commission rate, which rises the question: should those limits be hard-coded or modifiable by governance?

**Comment by jgo121** [comment]
I don't think it should be restrictive, some validators on Cosmos set the commission to 100% to just handle self stake on his validator. (Mainly for CEX managed validators - e.g. binance validator for Cosmos Hub)

**Comment by asmodat** [comment]
@jgo121, the 0 fee validators should not exist otherwise the free market will destroy the small validator business, the 50% max is essential to prevent CEX from offering staking products that are more favorable than native staking, it's a danger to the network.

**Comment by jgo121** [comment]
Added validation to be from 1% - 50% on this commit
https://github.com/KiraCore/sekai/pull/491/commits/e7bc45e373c01a5a32b29cd86e2f8b038fef649d
