### ISSUE TITLE
Auto-compounding mode triggers multiple bank calls to send small amounts of tokens at each block. 

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#432]
### Status quo

Auto-compound works as follow
- It sends the rewards to be compounded to its delegator address :
https://github.com/KiraCore/sekai/blob/55d47a7fee8573efa611100b778e7094e41f6e40/x/multistaking/keeper/delegation.go#L219

- it then triggers a Delegation() call on behalf of the user which sends those coins back to the module for staking:
https://github.com/KiraCore/sekai/blob/55d47a7fee8573efa611100b778e7094e41f6e40/x/multistaking/keeper/delegation.go#L305

- and then an other bank call is made to send the corresponding pool derivative `poolCoins` to the delegator:
https://github.com/KiraCore/sekai/blob/55d47a7fee8573efa611100b778e7094e41f6e40/x/multistaking/keeper/delegation.go#L329

[This is done at each block](https://github.com/KiraCore/sekai/blob/55d47a7fee8573efa611100b778e7094e41f6e40/x/distributor/keeper/abci.go#L31) which is an huge overhead for sekai to handle as the number of delegators grows.

### Enhancement 

- [ ] Current documentation suggest to use [SetDelegatorRewards()](https://github.com/KiraCore/sekai/blob/55d47a7fee8573efa611100b778e7094e41f6e40/x/multistaking/keeper/delegation.go#L92) instead, to store the `poolCoins`, which becomes claimable like standard rewards: 

> When enabled, rewards are automatically added to the delegator's stake. However, the corresponding staking derivatives are not sent to the delegator's address, as this would be too much of an overhead for the module to handle.

**Comment by jgo121** [comment]
Autocompound would be done only when enough number of tokens are on the rewards pool - this was already handled I guess at the time of implementation

**Comment by kmlbgn** [comment]
> Autocompound would be done only when enough number of tokens are on the rewards pool - this was already handled I guess at the time of implementation

Can you double check this ? as I'm unable to locate this test in here : 
https://github.com/KiraCore/sekai/blob/70e08655a09c554e1f30d2a7bbee0ccf11f48478/x/multistaking/keeper/delegation.go#L199-L233

**Comment by jgo121** [comment]
Looks like autocompound does not have minimum threshold implemented, I think it would be better to execute this once 8640 blocks are gone to make the process ideal, 8640 blocks are equivalent to around twice per day.
