### ISSUE TITLE
Allow selective basket withdrawals + support for multi-asset swaps.

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#442]
### Status quo 

Currently, when performing a basket withdrawal `burn-basket-tokens`, it is not possible to select specific tokens to withdraw. Instead, the withdrawal will rebalance the pool's weights, which may lead to a higher proportion of a particular token if the pool was initially imbalanced. The swap `swap-basket-tokens` enables the replacement of undesired tokens, but it is limited to one-to-one transfers. 

### Enhancement request

- [ ] Selective withdrawals
- [x] Multi-asset swaps

> Token Baskets implement a simple swap mechanism that enables users to exchange one or multiple basketed tokens for a set of specific ones. This function provides a convenient way for users to consolidate their holdings into a desired set of tokens. However, the swap incurs a fixed `swap_fee` and a variable `slippage_fee` with a minimum `slippage-fee-min` defined in the basket properties. The fees are calculated dynamically based on the degree to which the swap is disbalancing the basket. The greater the disbalance, the higher the "slippage" penalty will be. The slippage is a programmatic function and do not result from a changes in token value as seen in Liquidity Pools, as the value of all tokens remains constant.
> 
> A crucial aspect of the swap mechanism is that the sum of products of individual token amounts and their weights remain constant before and after the swap. This is expressed mathematically as:
> 
> $$
> \left \lfloor{ \sum_{i=0}^{tokens.Length - 1}tokens[i].weight \cdot tokens[i].amount}\right \rfloor  = constant
> $$
> 
> This means that the cumulative value of the tokens in the basket remain unchanged (or slightly larger due to rounding errors). Any additional tokens due to the applied slippage is accounted for in the `surplus`, while the `basket_swap_fee` is be paid to the network as a fee reward. This ensures that the value of the basket remains constant, providing stability to the system.

**Comment by jgo121** [comment]
Withdrawal of multiple tokens would be painful since it is not easy to calculate the out amount for each token.
But if required, we can support one token withdrawal. It's same for multitoken swap as well - multitoken swap does not have use case on users I think. (They can do the swap twice)

**Comment by jgo121** [comment]
Can you close this issue ticket after checking the implementation @kmlbgn ?

**Comment by kmlbgn** [comment]
Will do this require a bit of testing
