### ISSUE TITLE
Unused 'prototype' bank wrappers

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#453]
Those bank tx wrappers in `x/feeprocessing` doesn't seem to be used in the codebase at the moment. Consider cleaning.

https://github.com/KiraCore/sekai/blob/425b54bfa8ab064a966b7874a8e1580f1b4dd702/x/feeprocessing/keeper/keeper.go#L57

**Comment by jgo121** [comment]
The one mentioned is used here
https://github.com/KiraCore/sekai/blob/425b54bfa8ab064a966b7874a8e1580f1b4dd702/x/feeprocessing/keeper/keeper.go#L160

**Comment by jgo121** [comment]
Btw, I have found that return value is not checked on the call and added the check.
