### ISSUE TITLE
Review proposer_voters_count CLI and rename it

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#466]
`proposer_voters_count` is not very clear and look like a testing CLI. 
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/query.go#L652

If the purpose is to count all existing governance member, a.k.a councilors, it should be explicit. Also format should use "-" instead of "_". e.g.: `councilors-count`

**Comment by jgo121** [comment]
This is returning proposers count and voters count seprately - and therefore, updated to `proposers-voters-count`
```
// QueryProposerVotersCountResponse is the response type for Query/ProposerVotersCount RPC method.
type QueryProposerVotersCountResponse struct {
	Proposers uint64 `protobuf:"varint,1,opt,name=proposers,proto3" json:"proposers,omitempty"`
	Voters    uint64 `protobuf:"varint,2,opt,name=voters,proto3" json:"voters,omitempty"`
}
```
