### ISSUE TITLE
Inconsistent usage of FlagAddress and FlagAddr in gov client package CLI

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#467]
Current `cli` package `address` flag of the `x/gov` module is instantiated with `FlagAddress`

https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L36

But it is called with `FlagAddr` everywhere 

https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L669

**Comment by MrLutik** [comment]
![Screenshot_20230502-082631_Brave.jpg](https://user-images.githubusercontent.com/70693118/235594383-7ad5c42a-06f6-4954-85b7-2c38e9aa7195.jpg)

![Screenshot_20230502-082854_Brave.jpg](https://user-images.githubusercontent.com/70693118/235594647-11f4091e-35ee-4dd8-abf4-7521d0cee60d.jpg)

Looks like they have different values.

**Comment by kmlbgn** [comment]
`FlagAddr` is from a different module, `x/staking`. This issue is for the `x/gov` only
