### ISSUE TITLE
GOV module CLI refactoring

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#468]
- [x] `assign-role role` should be renamed `assign-role`
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L854

- [ ] `create` should be renamed `create-role` 
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L612

- [x] Several CLI are displaying `--whitelist_perms` and `--blacklist_perms` for no reason
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L1610-L1611

- [x] Several CLI showing `[role_id]` instead of `[role_sid]` and should be renamed
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L580

- [x] Several CLI showing `[role_description]` instead of `[permission_id] `
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/gov/client/cli/tx.go#L1619

**Comment by jgo121** [comment]
```
 create should be renamed create-role
```
This one is incorrect finding I guess. the transaction is `sekaid tx gov role create`

**Comment by jgo121** [comment]
Rest of them are handled on PR #472
