### ISSUE TITLE
TokenAlias typo

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#471]
Multiple `TokenAlians` typo in [x/tokens/proposal_handler.go](https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/tokens/proposal_handler.go#L28)
https://github.com/KiraCore/sekai/blob/b392371262a91eefabf8fc8e3aebb1acec6baa8e/x/tokens/proposal_handler.go#L28

**Comment by MrLutik** [comment]
![Screenshot_20230502-081832_Brave](https://user-images.githubusercontent.com/70693118/235593150-53fe8a64-6c11-4403-828a-83aa6c64af0a.jpg)
There are more.
