### ISSUE TITLE
Allow governance to parameterize veto threshold + set default threshold at 33.40%

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#479]
Veto rejection rule is useless because it is the same has the standard rejection rule (if everything else than Yes is >= 50%) 
This is due to deprecation of Network Actor vote-type permissions feature. 

https://github.com/KiraCore/sekai/blob/5bced5dcb112a3c4f5f50a5d6aeb49bd76254d1a/x/gov/types/vote.go#L58-L64

Therefore, veto threshold should be governance defined through network property and set to default 33.40%.

**Comment by jgo121** [comment]
Hmm, would this be required to change veto threshold to be governance parameter @asmodat ?

**Comment by kmlbgn** [comment]
It appears that @kobs30 has made an attempt in adding a veto network properties that never made it to master : https://github.com/KiraCore/sekai/compare/feature/poll_proposal_v2
