### ISSUE TITLE
Clarification or Removal of the SetFeesCollected Function

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#482]
> @jgo121 : Set Fees collected handles the intermediary balance for fees collected on fee collector module. It's instantly distributed to the validator and the delegators FYI

The `SetFeesCollected` function appears to be obsolete, as it's not invoked anywhere in the codebase except during Init and export genesis operations. 
Consider removing if it's no longer needed or adding comprehensive code comments explaining its purpose and future usage possibilities.

https://github.com/KiraCore/sekai/blob/e57365bbf24ef2db0de3e561d1c9ade118111f9f/x/distributor/keeper/store.go#L11-L27

**Comment by jgo121** [comment]
Removed
