### ISSUE TITLE
Wrong poll result calculation and veto threshold

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#483]
- [ ] The current mechanism for calculating poll results and handling vetoes needs to be updated to align with the recommendations proposed in the KIP : 

- a poll should be considered passed if any individual option receives a majority of votes, rather than requiring a cumulative majority across all options. 
- a poll is rejected if more than one option have equal AND highest number of votes, leading to an inconclusive result.

https://github.com/KiraCore/sekai/blob/e57365bbf24ef2db0de3e561d1c9ade118111f9f/x/gov/types/poll_vote.go#L36-L57

- [ ] In addition, the veto threshold in the existing system is set at 50%, due to deprecation of Network Actor. Poll vetoes threshold should be tied with proposal veto threshold and configurable through governance cf. #479 

- [ ] #484

**Comment by jgo121** [comment]
Is this being handled @kobs30 ?
