### ISSUE TITLE
Missing x/gov network properties 

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#485]
The following network properties are missing : 
- `max_proposal_title_size`
- `max_proposal_description_size`
- `max_proposal_poll_option_size` (cf. #484 )
- `max_proposal_poll_option_count` (cf. #484 )

**Comment by kobs30** [comment]
Defined all these properties: proto/kira/gov/network_properties.proto:58-61 
Using; x/gov/keeper/msg_server.go:153,157,179 and 169
