### ISSUE TITLE
`upset-staking-pool`'s `--commission` flag error message is not explicit

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#496]
the `--commission` flag of `upset-staking-pool` is required, but the help and/or the error message isn't explicit for the user when missing.

<img width="1130" alt="image" src="https://github.com/KiraCore/sekai/assets/59659182/84cce4ea-98c8-4abd-9104-91ced6a3e195">

**Comment by kmlbgn** [comment]
good opportunity to change the command Usage description `[validator] `to `[validator key]`

**Comment by jgo121** [comment]
Handled on this commit
https://github.com/KiraCore/sekai/pull/491/commits/a3673d6d3b013a9151a09e577b0f4e99b25b8809
