### ISSUE TITLE
Sekaid version installed is lower than downloaded release version

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#504]
There is this strange issue that the installed sekaid version is consistently lower than the release version being downloaded (cf. screenshot `0.3.16`/`0.3.15.1`). Checkin the commit since release https://github.com/KiraCore/sekai/compare/v0.3.16...master we can notice the actual merge of 0.3.16 directly following the release. 

![image](https://github.com/KiraCore/sekai/assets/59659182/103d1934-9f22-45bc-9a9e-99b7bd2cc7c9)

**Comment by MrLutik** [comment]
Each tag refer to previous version release.

```
git checkout v0.3.17
```
tag v0.3.17 refer to -> release/v0.3.16

@kobs30 @jgo121
 
That should be fixed and consistency restored. 

In case this is a feature we should add documentation.

**Comment by jgo121** [comment]
I think this is issue with CI/CD - would like to get opinion from @asmodat

**Comment by jgo121** [comment]
@asmodat  said it's been already resolved, can we close this issue after check @kmlbgn

**Comment by kmlbgn** [comment]
@MrLutik is on it, needs testing. Will close when it passes
