### ISSUE TITLE
Setting execution fees for existing sekai `Msg` is not associated to a governance proposal

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#554]
### Status Quo

Currently, only sudo users can change execution fees. There is no governance proposal and associated permissions. 

### Proposed Change

There should exist a governance process to do so, especially as we roll into mainnet where most of sudo permissions will be deprecated.

**Comment by jgo121** [comment]
We already have set execution fees proposal and permissions available now and would be good to close this ticket @kmlbgn - and duplicated ticket exists - https://github.com/KiraCore/sekai/issues/626
