### ISSUE TITLE
Soft forks are currently not supported 

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#580]
### Status Quo
The upgrade module currently does not support soft forks (`instate_upgrade = false`). The [ApplyUpgradePlan](https://github.com/KiraCore/sekai/blob/f883a347fbde7e3fae0933532f1217cfc33616ac/x/upgrade/keeper/plan.go#L67) function panics when `instate_upgrade` is set to `false`.

### Proposed Change
Soft forks without a change in the sekai binary are not feasible. The binary version of sekai is critical for determining when the network should restart after an upgrade. Therefore, the `instate_upgrade` parameter should be deprecated, and appropriate logic should be introduced to handle soft forks and proceeds a binary version change.

**Comment by jgo121** [comment]
```
		if plan.InstateUpgrade == false {
			panic(fmt.Sprintf("UPGRADE \"%s\" NEEDED at upgrade_time=%s", plan.Name, time.Unix(plan.UpgradeTime, 0).String()))
		}
```
This is correct, instateUpgrade false means, hard fork, and true means soft fork
