### ISSUE TITLE
Basket swaps `outAmount` logic is using `RoundInt()` which can round up

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#590]
### Status Quo 

Currently, the swaps logic defining the amount of token the user receives,`outAmount`, uses RoundInt() which can round up if the number is above halfway.

https://github.com/KiraCore/sekai/blob/7027803bae9408b973a3ebc7bdbe9394df8aabf3/x/basket/keeper/mint_burn_swap.go#L237

### Proposed Change 

According to KIP, the logic should use a floor function or any logic that would always round down leaving excess tokens in the basket. It seems the Cosmos SDK provides a `TruncateInt()`.

> Note that we use inequality sign >= in the equation above because when tokens are being withdraws we can’t transfer “fractions” thus we use a floor function - this results in excess tokens remaining in the basket.
> (...)
> **The basket should return to the user amount of tokens `B` NOT greater than:**
> - `B = floor((A_weight*A_amount) + (D_weight*D_amount) / B_weight) = floor(((0.2*100) + (1.33*10)) / 0.7) = floor(33.3 / 0.7) = 47`

**Comment by jgo121** [comment]
I think this is not an issue, everywhere on Cosmos, it uses RoundInt without any problem
