### ISSUE TITLE
Token baskets lack total derivative circulation supply tracking and do not perform weights check during governance updates

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#592]
### Status Quo 
Currently, the system keeps historical records of the amounts of basket tokens minted, burned, and swapped over time in baskets. However, any data older than the defined `LimitsPeriod` is pruned at the end of each block. There is neither a specific function nor a record to continuously monitor the net circulating supply of basket derivative tokens (i.e., total mints minus total burns).

https://github.com/KiraCore/sekai/blob/7027803bae9408b973a3ebc7bdbe9394df8aabf3/x/basket/abci.go#L15-L22

This poses a considerable challenge, especially during updates by governance, which have been left unsolved. The `EditBasket()` function currently lacks checks to verify if the modified parameters align with the total circulating derivative supply. Therefore it is possible for governance to set weights in a way that there wouldn't be enough aggregated tokens to redeem against the amount of basket derivatives in circulation.

https://github.com/KiraCore/sekai/blob/7027803bae9408b973a3ebc7bdbe9394df8aabf3/x/basket/keeper/basket.go#L106-L113

### Proposed Changes

The KIP recommends that an edit proposal should be declined if the new parameters don't adhere to a specific equation:
**(Note the EQ OR GT)**

> The governance must ensure that the weights of each token in the basket are properly configured to maintain the value of the issued basket tokens. Should the governance decide to re-configure one or many of the weight properties of the basket (for example due to peg changes), it is important to ensure that the sum of the products of the weight and amount of each token in the basket must be greater than or equal to the amount of issued basket tokens `B<ID>/<denom>` otherwise there will not be enough tokens in the basket to redeem. For example, if the basket B<ID> includes tokens A, B, and C, the governance must ensure that `(A_amount * A_weight) + (B_amount * B_weight) + (C_amount * C_weight) >= B_<ID>/<denom>.total_amount_issued`
 If the weights are not correctly configured, the governance proposal to update the basket weights will fail.
/code

Hence each basket should be able to track its circulating derivative supply and relevant check should be added to the `EditBasket()` function to align with desired mechanism.

**Comment by jgo121** [comment]
```go
	usedDenom := make(map[string]bool)
	for index, token := range basket.Tokens {
		// ensure tokens amount is derivated from previous by denom
		basket.Tokens[index].Amount = prevAmounts[token.Denom]

		// validate denom for the token
		if err := sdk.ValidateDenom(token.Denom); err != nil {
			return err
		}
		if token.Weight.IsZero() {
			return types.ErrTokenWeightShouldNotBeZero
		}
		if usedDenom[token.Denom] {
			return types.ErrDuplicateDenomExistsOnTokens
		}
		usedDenom[token.Denom] = true
	}

	k.SetBasket(ctx, basket)
```
Here's the codebase where it sets the amount same as previous one - therefore as part of the proposal, the total derivatives basket does not change.
