### ISSUE TITLE
Inefficient `tokens_cap` validation during mint, burn and swap operations

### ISSUE THREAD

**Issue by kmlbgn** [KiraCore/sekai#593]
### Status Quo 

The `tokens_cap` parameter sets a limit on the maximum weight-adjusted share a specific aggregated token can have in the basket, ensuring that no single token dominates the basket's value.

The current `ValidateTokensCap` function, as provided computes the total weight-adjusted token amounts in the basket for all tokens and checks if any token exceeds the `tokens_cap` during swaps, mints and burns. This means that even if a user is depositing a single token type, the validation runs for all token types in the basket. This is inefficient assuming token baskets can generate a lot of volume and have a lot of different aggregated coins. 

https://github.com/KiraCore/sekai/blob/7027803bae9408b973a3ebc7bdbe9394df8aabf3/x/basket/types/basket.go#L87-L99

### Proposed Changes 

An optimized approach would be to compute the total weight-adjusted token amounts in the basket once (since this value would be needed for any token being deposited). For each token being deposited, check if its updated weight-adjusted amount would exceed the `tokens_cap`. This way, the loop would only run for the tokens being deposited, rather than all tokens in the basket. The computational complexity would be reduced, especially if the basket contains many tokens but only a few are involved in the transaction.

**Comment by jgo121** [comment]
The complexity of this operation is not high, it does not spend any gas as well. The number of tokens won't exceed 500 (number of validators). And 500 loop is pretty low especially for this operation which is just doing comparison.
