### ISSUE TITLE
Kira node often gets 'inactive' status with a stable machine 

### ISSUE THREAD

**Issue by tieppv** [KiraCore/sekai#92]
Hi Kira team,

My node often gets 'inactive' status. I have run my node on VPS ( its very stable machine and network). So I need to check and re-active frequently. But the fee for re-active is 1000ukex. 
1. The kira nodes often get inactive status. 
2. The re-active fee too high so I cannot re-active my node ( insufficient balance)

Please check. Thanks team.

**Comment by asmodat** [comment]
This is going to be fixed with KIP_68 https://github.com/KiraCore/docs/blob/master/spec/iteration-2/kip_68.md
